### ISSUE TITLE
Markbot error — Functionality

### ISSUE THREAD

**Issue by matthewpeixoto** [matthewpeixoto/circle-maker#1]
The website seems to function properly but is getting the Markbot error shown below:

![screen shot 2017-05-06 at 8 00 13 pm](https://cloud.githubusercontent.com/assets/16690200/25776801/f1a60718-3296-11e7-9159-011c0347a36c.png)

@thomasjbradley

**Comment by matthewpeixoto** [comment]
Fixed it!

**Comment by thomasjbradley** [comment]
Fantastic!
